# Task 1: Make the API Calls

In [2]:
import requests
from bs4 import BeautifulSoup

In [7]:


# Step 1 — Get the list of top story IDs

url = 'https://hacker-news.firebaseio.com/v0/topstories.json'
response = requests.get(url)
top_story_ids = response.json()
data = response.json()

print(data)

[47760529, 47760764, 47755629, 47757495, 47760750, 47759709, 47761609, 47759341, 47716805, 47718284, 47761613, 47753472, 47708457, 47751781, 47761625, 47760925, 47728970, 47715389, 47752819, 47756321, 47753689, 47711148, 47761310, 47729046, 47750669, 47756772, 47729350, 47743728, 47728823, 47756569, 47758347, 47715256, 47759292, 47728192, 47756036, 47755573, 47755209, 47759416, 47760027, 47750872, 47752466, 47729694, 47751621, 47756876, 47751936, 47761105, 47754379, 47757552, 47746610, 47757469, 47757426, 47752884, 47750821, 47755604, 47744255, 47754179, 47757013, 47733217, 47760781, 47756672, 47748064, 47755734, 47754100, 47746577, 47741953, 47741701, 47760543, 47738827, 47759428, 47739313, 47758880, 47738094, 47756448, 47745284, 47737292, 47742200, 47747017, 47739260, 47758453, 47760273, 47741460, 47702887, 47758343, 47759433, 47758831, 47741527, 47719490, 47754559, 47737876, 47744132, 47724352, 47738864, 47757289, 47737542, 47750259, 47738978, 47749674, 47736476, 47757838, 47758651, 47743628, 47758028, 47741393, 47738883, 47759989, 47743096, 47759541, 47754480, 47756231, 47739174, 47738343, 47735535, 47743730, 47728879, 47755938, 47717690, 47759738, 47736555, 47706423, 47743819, 47744540, 47741531, 47757774, 47755805, 47758967, 47741889, 47719740, 47758802, 47730712, 47732020, 47749295, 47747595, 47756737, 47754329, 47758616, 47737376, 47742461, 47727960, 47694064, 47698455, 47757657, 47734878, 47729634, 47731838, 47706560, 47759079, 47757509, 47749222, 47758287, 47732402, 47691730, 47742261, 47727659, 47748314, 47687273, 47702890, 47756002, 47747248, 47722333, 47721955, 47730407, 47712656, 47698111, 47728653, 47738196, 47756711, 47733561, 47730194, 47697870, 47758863, 47719968, 47687443, 47733521, 47724118, 47713495, 47700556, 47730981, 47714273, 47721953, 47693559, 47759281, 47719942, 47697722, 47725403, 47735405, 47720418, 47758394, 47745120, 47731506, 47743700, 47717847, 47742790, 47701769, 47695213, 47737663, 47750519, 47733066, 47720419, 47704804, 47689793, 47727076, 47719602, 47719486, 47721997, 47722562, 47718470, 47719274, 47734822, 47757166, 47751265, 47756798, 47744683, 47757668, 47754002, 47731998, 47725583, 47708818, 47716490, 47707632, 47721946, 47710466, 47739305, 47730370, 47745300, 47732697, 47738514, 47712718, 47702541, 47743077, 47752636, 47685984, 47733971, 47750522, 47685320, 47757226, 47728323, 47735581, 47741544, 47755334, 47722011, 47716809, 47720719, 47751032, 47754606, 47698046, 47707762, 47688678, 47705413, 47732945, 47686549, 47745543, 47701100, 47756497, 47687248, 47702647, 47735779, 47721255, 47741892, 47702196, 47709130, 47741634, 47699470, 47745261, 47742002, 47760633, 47701148, 47751669, 47730522, 47709158, 47703805, 47691464, 47727711, 47745230, 47689237, 47700972, 47743447, 47753437, 47694983, 47749497, 47753026, 47726340, 47693153, 47702499, 47707477, 47742680, 47730229, 47705187, 47695012, 47706140, 47724921, 47734912, 47722262, 47703419, 47750931, 47744060, 47722096, 47691538, 47686046, 47731707, 47718812, 47704013, 47689648, 47720827, 47744510, 47701233, 47741512, 47710007, 47737383, 47725559, 47758029, 47745222, 47744598, 47751619, 47706268, 47736071, 47699181, 47757210, 47715339, 47695815, 47690977, 47693679, 47685945, 47685644, 47741449, 47695666, 47748036, 47758502, 47689174, 47696035, 47738520, 47706141, 47741557, 47736291, 47685739, 47686431, 47729069, 47759990, 47713113, 47752489, 47703123, 47759161, 47701572, 47692043, 47756930, 47689165, 47759037, 47694036, 47712134, 47700388, 47743878, 47708041, 47709251, 47704285, 47760304, 47717447, 47714573, 47721207, 47710149, 47734856, 47726784, 47689550, 47719975, 47690797, 47753643, 47736331, 47736298, 47684514, 47747625, 47696562, 47733479, 47690609, 47729994, 47710907, 47710835, 47733265, 47733229, 47704259, 47700662, 47683376, 47718891, 47693960, 47737899, 47703065, 47735121, 47692661, 47745714, 47713584, 47737469, 47737387, 47704430, 47759176, 47758490, 47689319, 47736289, 47731049, 47687464, 47690405, 47726041, 47740315, 47723243, 47736834, 47698512, 47749544, 47744585, 47703528, 47752301, 47719522, 47712222, 47757174, 47732623, 47736217, 47750069, 47743686, 47755118, 47716617, 47722566, 47722913, 47708817, 47700460, 47713265, 47710782, 47704443, 47731139, 47744905, 47704881, 47693585, 47727619, 47736814, 47698067, 47730540, 47699396, 47744544, 47736698, 47718694, 47697641, 47717514, 47748229, 47744259, 47744252, 47729975, 47702791, 47729925, 47683042, 47756653, 47690434, 47731927, 47720860, 47734397, 47734253, 47725243, 47719289, 47743117, 47736349, 47733222, 47735224, 47741998, 47741981, 47693047, 47750775, 47732249, 47732148, 47731987, 47727284, 47685685, 47729926, 47705802, 47741222, 47720862, 47687755, 47750086, 47684898, 47738397, 47704687, 47725765, 47731378, 47719485, 47726369, 47730916, 47718607, 47730799, 47708411, 47722081, 47691686, 47691466, 47711623, 47708697, 47717292, 47743123, 47743088, 47717587, 47722136, 47706555, 47736831, 47742652, 47738917, 47723647, 47692603, 47720060, 47750974, 47733106]

In [13]:
# Fetch 500 IDs from the returned array

first_500_story_ids = top_story_ids[:500]
display(first_500_story_ids)

[47760529,
 47760764,
 47755629,
 47757495,
 47760750,
 47759709,
 47761609,
 47759341,
 47716805,
 47718284,
 47761613,
 47753472,
 47708457,
 47751781,
 47761625,
 47760925,
 47728970,
 47715389,
 47752819,
 47756321,
 47753689,
 47711148,
 47761310,
 47729046,
 47750669,
 47756772,
 47729350,
 47743728,
 47728823,
 47756569,
 47758347,
 47715256,
 47759292,
 47728192,
 47756036,
 47755573,
 47755209,
 47759416,
 47760027,
 47750872,
 47752466,
 47729694,
 47751621,
 47756876,
 47751936,
 47761105,
 47754379,
 47757552,
 47746610,
 47757469,
 47757426,
 47752884,
 47750821,
 47755604,
 47744255,
 47754179,
 47757013,
 47733217,
 47760781,
 47756672,
 47748064,
 47755734,
 47754100,
 47746577,
 47741953,
 47741701,
 47760543,
 47738827,
 47759428,
 47739313,
 47758880,
 47738094,
 47756448,
 47745284,
 47737292,
 47742200,
 47747017,
 47739260,
 47758453,
 47760273,
 47741460,
 47702887,
 47758343,
 47759433,
 47758831,
 47741527,
 47719490,
 47754559,
 47737876,
 47744132,
 47724352,
 47738864,
 47757289,
 47737542,
 47750259,
 47738978,
 47749674,
 47736476,
 47757838,
 47758651,
 47743628,
 47758028,
 47741393,
 47738883,
 47759989,
 47743096,
 47759541,
 47754480,
 47756231,
 47739174,
 47738343,
 47735535,
 47743730,
 47728879,
 47755938,
 47717690,
 47759738,
 47736555,
 47706423,
 47743819,
 47744540,
 47741531,
 47757774,
 47755805,
 47758967,
 47741889,
 47719740,
 47758802,
 47730712,
 47732020,
 47749295,
 47747595,
 47756737,
 47754329,
 47758616,
 47737376,
 47742461,
 47727960,
 47694064,
 47698455,
 47757657,
 47734878,
 47729634,
 47731838,
 47706560,
 47759079,
 47757509,
 47749222,
 47758287,
 47732402,
 47691730,
 47742261,
 47727659,
 47748314,
 47687273,
 47702890,
 47756002,
 47747248,
 47722333,
 47721955,
 47730407,
 47712656,
 47698111,
 47728653,
 47738196,
 47756711,
 47733561,
 47730194,
 47697870,
 47758863,
 47719968,
 47687443,
 47733521,
 47724118,
 47713495,
 47700556,
 47730981,
 47714273,
 47721953,
 47693559,
 47759281,
 47719942,
 47697722,
 47725403,
 47735405,
 47720418,
 47758394,
 47745120,
 47731506,
 47743700,
 47717847,
 47742790,
 47701769,
 47695213,
 47737663,
 47750519,
 47733066,
 47720419,
 47704804,
 47689793,
 47727076,
 47719602,
 47719486,
 47721997,
 47722562,
 47718470,
 47719274,
 47734822,
 47757166,
 47751265,
 47756798,
 47744683,
 47757668,
 47754002,
 47731998,
 47725583,
 47708818,
 47716490,
 47707632,
 47721946,
 47710466,
 47739305,
 47730370,
 47745300,
 47732697,
 47738514,
 47712718,
 47702541,
 47743077,
 47752636,
 47685984,
 47733971,
 47750522,
 47685320,
 47757226,
 47728323,
 47735581,
 47741544,
 47755334,
 47722011,
 47716809,
 47720719,
 47751032,
 47754606,
 47698046,
 47707762,
 47688678,
 47705413,
 47732945,
 47686549,
 47745543,
 47701100,
 47756497,
 47687248,
 47702647,
 47735779,
 47721255,
 47741892,
 47702196,
 47709130,
 47741634,
 47699470,
 47745261,
 47742002,
 47760633,
 47701148,
 47751669,
 47730522,
 47709158,
 47703805,
 47691464,
 47727711,
 47745230,
 47689237,
 47700972,
 47743447,
 47753437,
 47694983,
 47749497,
 47753026,
 47726340,
 47693153,
 47702499,
 47707477,
 47742680,
 47730229,
 47705187,
 47695012,
 47706140,
 47724921,
 47734912,
 47722262,
 47703419,
 47750931,
 47744060,
 47722096,
 47691538,
 47686046,
 47731707,
 47718812,
 47704013,
 47689648,
 47720827,
 47744510,
 47701233,
 47741512,
 47710007,
 47737383,
 47725559,
 47758029,
 47745222,
 47744598,
 47751619,
 47706268,
 47736071,
 47699181,
 47757210,
 47715339,
 47695815,
 47690977,
 47693679,
 47685945,
 47685644,
 47741449,
 47695666,
 47748036,
 47758502,
 47689174,
 47696035,
 47738520,
 47706141,
 47741557,
 47736291,
 47685739,
 47686431,
 47729069,
 47759990,
 47713113,
 47752489,
 47703123,
 47759161,
 47701572,
 47692043,
 47756930,
 47689165,
 47759037,
 47694036,
 47712134,
 47700388,
 47743878,
 47708041,
 47709251,
 47704285,
 47760304,
 47717447,
 47714573,
 47721207,
 47710149,
 47734856,
 47726784,
 47689550,
 47719975,
 47690797,
 47753643,
 47736331,
 47736298,
 47684514,
 47747625,
 47696562,
 47733479,
 47690609,
 47729994,
 47710907,
 47710835,
 47733265,
 47733229,
 47704259,
 47700662,
 47683376,
 47718891,
 47693960,
 47737899,
 47703065,
 47735121,
 47692661,
 47745714,
 47713584,
 47737469,
 47737387,
 47704430,
 47759176,
 47758490,
 47689319,
 47736289,
 47731049,
 47687464,
 47690405,
 47726041,
 47740315,
 47723243,
 47736834,
 47698512,
 47749544,
 47744585,
 47703528,
 47752301,
 47719522,
 47712222,
 47757174,
 47732623,
 47736217,
 47750069,
 47743686,
 47755118,
 47716617,
 47722566,
 47722913,
 47708817,
 47700460,
 47713265,
 47710782,
 47704443,
 47731139,
 47744905,
 47704881,
 47693585,
 47727619,
 47736814,
 47698067,
 47730540,
 47699396,
 47744544,
 47736698,
 47718694,
 47697641,
 47717514,
 47748229,
 47744259,
 47744252,
 47729975,
 47702791,
 47729925,
 47683042,
 47756653,
 47690434,
 47731927,
 47720860,
 47734397,
 47734253,
 47725243,
 47719289,
 47743117,
 47736349,
 47733222,
 47735224,
 47741998,
 47741981,
 47693047,
 47750775,
 47732249,
 47732148,
 47731987,
 47727284,
 47685685,
 47729926,
 47705802,
 47741222,
 47720862,
 47687755,
 47750086,
 47684898,
 47738397,
 47704687,
 47725765,
 47731378,
 47719485,
 47726369,
 47730916,
 47718607,
 47730799,
 47708411,
 47722081,
 47691686,
 47691466,
 47711623,
 47708697,
 47717292,
 47743123,
 47743088,
 47717587,
 47722136,
 47706555,
 47736831,
 47742652,
 47738917,
 47723647,
 47692603,
 47720060,
 47750974,
 47733106]

In [16]:
# Step 2 — Get each story details; add headers

story_details = []
base_item_url = 'https://hacker-news.firebaseio.com/v0/item/{}.json'
headers = {"User-Agent": "TrendPulse/1.0"}

for story_id in first_500_story_ids:
    item_url = base_item_url.format(story_id)
  # adding a try-except block to handle failed requests
    try:
        response = requests.get(item_url, headers=headers)
        response.raise_for_status() # Raise an exception for bad status codes (4xx or 5xx)
        story_details.append(response.json())
    except requests.exceptions.RequestException as e:
        print(f"Failed to fetch story {story_id}: {e}")

# Verify the first 5 story details
display(story_details[:5])

[{'by': 'thebiblelover7',
  'descendants': 76,
  'id': 47760529,
  'kids': [47762055,
   47761254,
   47761911,
   47761226,
   47761025,
   47761498,
   47761916,
   47761079,
   47761849,
   47760821,
   47761286,
   47760973,
   47761017,
   47761807,
   47761367,
   47761039,
   47760893,
   47760785,
   47761076,
   47761306,
   47760878,
   47761266,
   47760813,
   47761241,
   47761855,
   47761115,
   47760995],
  'score': 337,
  'time': 1776133515,
  'title': 'DaVinci Resolve releases Photo Editor',
  'type': 'story',
  'url': 'https://www.blackmagicdesign.com/products/davinciresolve/photo'},
 {'by': 'zdw',
  'descendants': 105,
  'id': 47760764,
  'kids': [47761535,
   47761736,
   47761026,
   47761769,
   47761003,
   47761862,
   47761922,
   47761764,
   47761574,
   47761309,
   47761829,
   47760805,
   47761897,
   47761734,
   47761611,
   47761592,
   47761776,
   47761247,
   47761438,
   47761089,
   47761107,
   47761792,
   47761740,
   47761667,
   47761515,
   47761800,
   47761146,
   47761108,
   47761243],
  'score': 200,
  'time': 1776135987,
  'title': 'A new spam policy for "back button hijacking"',
  'type': 'story',
  'url': 'https://developers.google.com/search/blog/2026/04/back-button-hijacking'},
 {'by': 'speckx',
  'descendants': 241,
  'id': 47755629,
  'kids': [47756259,
   47755991,
   47756498,
   47756219,
   47758432,
   47761057,
   47761061,
   47757660,
   47757352,
   47760337,
   47756398,
   47760916,
   47755998,
   47757937,
   47757220,
   47759677,
   47760373,
   47761394,
   47757976,
   47756174,
   47760223,
   47755877,
   47757928,
   47760510,
   47756920,
   47759830,
   47758212,
   47757309,
   47758289,
   47759329,
   47758168,
   47757794,
   47757479,
   47757623,
   47756395,
   47755914,
   47761675,
   47756570,
   47761514,
   47760190,
   47759653,
   47757930,
   47760866,
   47758900,
   47756045,
   47756872,
   47756606],
  'score': 861,
  'time': 1776102879,
  'title': 'Someone bought 30 WordPress plugins and planted a backdoor in all of them',
  'type': 'story',
  'url': 'https://anchor.host/someone-bought-30-wordpress-plugins-and-planted-a-backdoor-in-all-of-them/'},
 {'by': 'ezekg',
  'descendants': 347,
  'id': 47757495,
  'kids': [47757695,
   47757981,
   47761842,
   47757617,
   47758067,
   47761360,
   47757721,
   47761936,
   47757989,
   47758359,
   47762008,
   47758698,
   47761295,
   47758572,
   47761301,
   47757789,
   47761626,
   47758749,
   47761501,
   47758232,
   47758929,
   47757606,
   47760509,
   47758787,
   47758209,
   47758047,
   47760839,
   47758533,
   47758365,
   47757658,
   47759148,
   47761020,
   47760456,
   47757770,
   47757646,
   47758173,
   47760473,
   47758722,
   47759725,
   47757713,
   47760080,
   47757996,
   47758436,
   47758977,
   47757688,
   47757736,
   47759290,
   47758888,
   47760497,
   47757896,
   47761317,
   47758824,
   47759197,
   47760753,
   47758087,
   47758034,
   47757692,
   47759880,
   47758177,
   47759135,
   47758085,
   47757655,
   47757611,
   47759069,
   47758939,
   47758242,
   47758031,
   47757918,
   47758642,
   47761065,
   47758150,
   47757867,
   47757614,
   47757822],
  'score': 630,
  'time': 1776112609,
  'title': 'GitHub Stacked PRs',
  'type': 'story',
  'url': 'https://github.github.com/gh-stack/'},
 {'by': 'zdw',
  'descendants': 30,
  'id': 47760750,
  'kids': [47762064,
   47761717,
   47761906,
   47761952,
   47762032,
   47762010,
   47761705,
   47761907,
   47761925,
   47761986,
   47761968,
   47761729,
   47761558,
   47761757],
  'score': 104,
  'time': 1776135860,
  'title': 'Sometimes powerful people just do dumb shit',
  'type': 'story',
  'url': 'https://www.joanwestenberg.com/sometimes-powerful-people-just-do-dumb-shit/'}]

In [17]:
# Assign a category to each story by checking whether its title contains any of these keywords:

import pandas as pd

categories = {
    'technology': ['AI', 'software', 'tech', 'code', 'computer', 'data', 'cloud', 'API', 'GPU', 'LLM'],
    'worldnews': ['war', 'government', 'country', 'president', 'election', 'climate', 'attack', 'global'],
    'sports': ['NFL', 'NBA', 'FIFA', 'sport', 'game', 'team', 'player', 'league', 'championship'],
    'science': ['research', 'study', 'space', 'physics', 'biology', 'discovery', 'NASA', 'genome'],
    'entertainment': ['movie', 'film', 'music', 'Netflix', 'game', 'book', 'show', 'award', 'streaming']
}

# Function to assign category
def assign_category(title):
    if title is None: # If a title is missing
        return 'Other'
    title_lower = title.lower()
    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword.lower() in title_lower:
                return category
    return 'Other'

# Assign categories to each story
for story in story_details:
    story['category'] = assign_category(story.get('title'))

# Display the first 5 stories with their new category
display(pd.DataFrame(story_details[:5]))

,by,descendants,id,kids,score,time,title,type,url,category
0,thebiblelover7,76,47760529,"[47762055, 47761254, 47761911, 47761226, 47761...",337,1776133515,DaVinci Resolve releases Photo Editor,story,https://www.blackmagicdesign.com/products/davi...,Other
1,zdw,105,47760764,"[47761535, 47761736, 47761026, 47761769, 47761...",200,1776135987,"A new spam policy for ""back button hijacking""",story,https://developers.google.com/search/blog/2026...,Other
2,speckx,241,47755629,"[47756259, 47755991, 47756498, 47756219, 47758...",861,1776102879,Someone bought 30 WordPress plugins and plante...,story,https://anchor.host/someone-bought-30-wordpres...,Other
3,ezekg,347,47757495,"[47757695, 47757981, 47761842, 47757617, 47758...",630,1776112609,GitHub Stacked PRs,story,https://github.github.com/gh-stack/,Other
4,zdw,30,47760750,"[47762064, 47761717, 47761906, 47761952, 47762...",104,1776135860,Sometimes powerful people just do dumb shit,story,https://www.joanwestenberg.com/sometimes-power...,Other

In [19]:
# Group stories by category and then iterate through those groups with 2 seconds time delay.

import time
from collections import defaultdict

categorized_stories = defaultdict(list)
for story in story_details:
    categorized_stories[story['category']].append(story)

for category, stories in categorized_stories.items():
    print(f"\n--- Category: {category.upper()} ---")
    for i, story in enumerate(stories[:3]): # Displaying first 3 stories from each category
        print(f"  Title: {story.get('title')}")
        if story.get('url'):
            print(f"  URL: {story.get('url')}")
        if i < 2 and len(stories) > 1: # Print a separator for readability
            print("  ------")
    time.sleep(2) # Wait 2 seconds before processing the next category

--- Category: OTHER ---
  Title: DaVinci Resolve releases Photo Editor
  URL: https://www.blackmagicdesign.com/products/davinciresolve/photo
  ------
  Title: A new spam policy for "back button hijacking"
  URL: https://developers.google.com/search/blog/2026/04/back-button-hijacking
  ------
  Title: Someone bought 30 WordPress plugins and planted a backdoor in all of them
  URL: https://anchor.host/someone-bought-30-wordpress-plugins-and-planted-a-backdoor-in-all-of-them/

--- Category: SPORTS ---
  Title: Nothing Ever Happens: Polymarket bot that always buys No on non-sports markets
  URL: https://github.com/sterlingcrispin/nothing-ever-happens
  ------
  Title: How long-distance couples use digital games to facilitate intimacy (2025)
  URL: https://arxiv.org/abs/2505.09509
  ------
  Title: Show HN: Equirect – a Rust VR video player
  URL: https://github.com/greggman/equirect

--- Category: TECHNOLOGY ---
  Title: Rust Threads on the GPU
  URL: https://www.vectorware.com/blog/threads-on-gpu/
  ------
  Title: Multi-Agentic Software Development Is a Distributed Systems Problem
  URL: https://kirancodes.me/posts/log-distributed-llms.html
  ------
  Title: Write less code, be more responsible
  URL: https://blog.orhun.dev/code-responsibly/

--- Category: ENTERTAINMENT ---
  Title: Show HN: Ithihāsas – a character explorer for Hindu epics, built in a few hours
  URL: https://www.ithihasas.in
  ------
  Title: Show HN: Continual Learning with .md
  URL: https://github.com/SunAndClouds/ReadMe
  ------
  Title: Show HN: boringBar – a taskbar-style dock replacement for macOS
  URL: https://boringbar.app/

--- Category: SCIENCE ---
  Title: The Physics of GPS
  URL: https://perthirtysix.com/how-does-gps-work
  ------
  Title: NASA Moon Base User's Guide [pdf]
  URL: https://www.nasa.gov/wp-content/uploads/2026/04/moon-base-architecture-users-guide.pdf
  ------
  Title: The Bra-and-Girdle Maker That Fashioned the Impossible for NASA
  URL: https://thereader.mitpress.mit.edu/the-bra-and-girdle-maker-that-fashioned-the-impossible-for-nasa/

--- Category: WORLDNEWS ---
  Title: Warp
  URL: https://blog.cloudflare.com/post-quantum-warp/
  ------
  Title: Chimpanzees in Uganda locked in eight-year 'civil war', say researchers
  URL: https://www.bbc.com/news/articles/cr71lkzv49po
  ------
  Title: JSON formatter Chrome plugin now closed and injecting adware
  URL: https://github.com/callumlocke/json-formatter

# Task 2: Extract the Fields

In [20]:
#  2. Extract the Fields

import datetime

processed_stories = []

for category, stories in categorized_stories.items():
    stories_in_category = 0
    for story in stories:
        if stories_in_category >= 25:
            break

        # Extract relevant fields
        processed_story = {
            'post_id': story.get('id'),
            'title': story.get('title'),
            'category': story.get('category'),
            'score': story.get('score'),
            'num_comments': story.get('descendants'),
            'author': story.get('by'),
            'collected_at': datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") # Current date and time
        }
        processed_stories.append(processed_story)
        stories_in_category += 1

# Display the first 15 collected stories to verify
display(pd.DataFrame(processed_stories).head(15))

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31
5,47759709,Lean proved this program correct; then I found...,Other,206,107,bumbledraven,2026-04-14 07:07:31
6,47761609,TanStack Start Now Support React Server Compon...,Other,23,20,polywock,2026-04-14 07:07:31
7,47759341,WiiFin – Jellyfin Client for Nintendo Wii,Other,124,55,throwawayk7h,2026-04-14 07:07:31
8,47716805,Anastasia (1997) live action reference material,Other,15,1,hyperific,2026-04-14 07:07:31
9,47718284,Design and implementation of DuckDB internals,Other,95,8,mpweiher,2026-04-14 07:07:31
10,47761613,UpDown: Efficient Manycore based on Many Threa...,Other,4,0,matt_d,2026-04-14 07:07:31
11,47751781,US appeals court declares 158-year-old home di...,Other,368,251,t-3,2026-04-14 07:07:31
12,47760925,"Hacker compromises A16Z-backed phone farm, cal...",Other,122,32,wibbily,2026-04-14 07:07:31
13,47715389,"I shipped a transaction bug, so I built a linter",Other,28,3,leonhfr,2026-04-14 07:07:31
14,47752819,Make tmux pretty and usable (2024),Other,352,221,speckx,2026-04-14 07:07:31

# Task 3: Save to JSON File

In [29]:
# 3. Saving to a JSON file

import os
import datetime

# Create the 'data' folder if it doesn't exist already
data_dir = 'data/'
os.makedirs(data_dir, exist_ok=True)

# Generate the filename with the current date
current_date = datetime.datetime.now().strftime("%Y%m%d")
filename = f"trends_{current_date}.json"
file_path = os.path.join(data_dir, filename)

# Convert the list of dictionaries to a pandas DataFrame and save to JSON
df_processed_stories = pd.DataFrame(processed_stories)
df_processed_stories.to_json(file_path, orient='records', indent=4)

print(f"All collected stories saved to: {file_path}")
print(f"Total stories collected: {len(processed_stories)}")

All collected stories saved to: data/trends_20260414.json
Total stories collected: 108

In [24]:
# Verify the contens of saved JSON file

import pandas as pd

# Read the JSON file into a pandas DataFrame
df_read = pd.read_json(file_path)

# Display the first few rows of the DataFrame
display(df_read.head())

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

The "Processed Stories" list now contains up to 25 stories for each category with the specified fields and a "collected_at" timestamp.

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive