# 1. Load the JSON File

In [13]:
import pandas as pd

# Pick the JSON file from 'data/' folder that's saved during Task 1.
try:
    df = pd.read_json('/content/drive/MyDrive/Colab Notebooks/trends_20260414.json')
    print(f"\nSuccessfully loaded {df.shape[0]} rows from trends_20260414.json")

except FileNotFoundError:
    print("Error: '/content/drive/MyDrive/Colab Notebooks/trends_20260414.json' not found. Please ensure the file exists in the specified path.")
except Exception as e:
    print(f"An error occurred while loading the JSON file: {e}")

Successfully loaded 108 rows from trends_20260414.json

# 2. Clean the Data

### Remove Duplicates

In [14]:
print(f"Initial number of rows: {df.shape[0]}")
df.drop_duplicates(subset='post_id', inplace=True)
print(f"Number of rows after removing duplicate post_ids: {df.shape[0]}")
display(df.head())

Initial number of rows: 108
Number of rows after removing duplicate post_ids: 108

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

### Handle Missing Values

In [15]:
print(f"Number of rows before dropping rows with missing critical values: {df.shape[0]}")
df.dropna(subset=['post_id', 'title', 'score'], inplace=True)
print(f"Number of rows after dropping rows with missing critical values: {df.shape[0]}")
display(df.head())

Number of rows before dropping rows with missing critical values: 108
Number of rows after dropping rows with missing critical values: 108

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

### Convert Data Types

In [16]:
print("DataFrame info before type conversion:")
df.info()

# Convert 'score' to integer, coercing errors to NaN
df['score'] = pd.to_numeric(df['score'], errors='coerce')
# Convert 'num_comments' to integer, coercing errors to NaN
df['num_comments'] = pd.to_numeric(df['num_comments'], errors='coerce')

# Drop rows where 'score' or 'num_comments' became NaN due to coercion errors
df.dropna(subset=['score', 'num_comments'], inplace=True)

# Convert to integer type after handling NaNs
df['score'] = df['score'].astype(int)
df['num_comments'] = df['num_comments'].astype(int)

print("\nDataFrame info after type conversion:")
df.info()
display(df.head())

DataFrame info before type conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       108 non-null    int64
 1   title         108 non-null    object
 2   category      108 non-null    object
 3   score         108 non-null    int64
 4   num_comments  108 non-null    int64
 5   author        108 non-null    object
 6   collected_at  108 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 6.0+ KB

DataFrame info after type conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       108 non-null    int64
 1   title         108 non-null    object
 2   category      108 non-null    object
 3   score         108 non-null    int64
 4   num_comments  108 non-null    int64
 5   author        108 non-null    object
 6   collected_at  108 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 6.0+ KB

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

### Filter Low Quality Stories

In [17]:
print(f"Number of rows before filtering by score: {df.shape[0]}")
df = df[df['score'] >= 5]
print(f"Number of rows after filtering for score >= 5: {df.shape[0]}")
display(df.head())

Number of rows before filtering by score: 108
Number of rows after filtering for score >= 5: 105

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

### Clean Whitespace in Title

In [18]:
print("Sample titles before stripping whitespace:")
print(df['title'].head().tolist())

df['title'] = df['title'].str.strip()

print("\nSample titles after stripping whitespace:")
print(df['title'].head().tolist())
display(df.head())

Sample titles before stripping whitespace:
['DaVinci Resolve releases Photo Editor', 'A new spam policy for "back button hijacking"', 'Someone bought 30 WordPress plugins and planted a backdoor in all of them', 'GitHub Stacked PRs', 'Sometimes powerful people just do dumb shit']

Sample titles after stripping whitespace:
['DaVinci Resolve releases Photo Editor', 'A new spam policy for "back button hijacking"', 'Someone bought 30 WordPress plugins and planted a backdoor in all of them', 'GitHub Stacked PRs', 'Sometimes powerful people just do dumb shit']

/tmp/ipykernel_1466/1156914008.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].str.strip()

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

### Gist of Cleaned Data

In [19]:
print(f"Final number of rows: {df.shape[0]}")
df.info()
display(df.head())

Final number of rows: 105
<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 0 to 107
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       105 non-null    int64
 1   title         105 non-null    object
 2   category      105 non-null    object
 3   score         105 non-null    int64
 4   num_comments  105 non-null    int64
 5   author        105 non-null    object
 6   collected_at  105 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 6.6+ KB

,post_id,title,category,score,num_comments,author,collected_at
0,47760529,DaVinci Resolve releases Photo Editor,Other,337,76,thebiblelover7,2026-04-14 07:07:31
1,47760764,"A new spam policy for ""back button hijacking""",Other,200,105,zdw,2026-04-14 07:07:31
2,47755629,Someone bought 30 WordPress plugins and plante...,Other,861,241,speckx,2026-04-14 07:07:31
3,47757495,GitHub Stacked PRs,Other,630,347,ezekg,2026-04-14 07:07:31
4,47760750,Sometimes powerful people just do dumb shit,Other,104,30,zdw,2026-04-14 07:07:31

# 3. Save as CSV

In [20]:
import os

# Define the directory for saving the clean data
output_dir = 'data/'

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Define the output file path
output_file_path = os.path.join(output_dir, 'trends_clean.csv')

# Save the cleaned DataFrame to CSV
df.to_csv(output_file_path, index=False)

print(f"Successfully saved {df.shape[0]} rows to {output_file_path}")

Successfully saved 105 rows to data/trends_clean.csv

### Stories Per Category Summary

In [21]:
stories_per_category = df['category'].value_counts()
print("Number of stories per category:")
display(stories_per_category)

Number of stories per category:

category
technology       25
Other            24
entertainment    24
worldnews        13
sports           12
science           7
Name: count, dtype: int64